name: Auto Formatter

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install black isort prettier
      - name: Run formatters
        run: |
          black .
          isort .
          prettier --write "**/*.yml" "**/*.md"
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply code formatters"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
